//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programlancer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimeClock {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeClock() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Programlancer.TimeClock", typeof(TimeClock).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string strAll {
            get {
                return ResourceManager.GetString("strAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and mail sent.
        /// </summary>
        internal static string strAndMailSent {
            get {
                return ResourceManager.GetString("strAndMailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at work already.
        /// </summary>
        internal static string strAtWorkAlready {
            get {
                return ResourceManager.GetString("strAtWorkAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackUp.
        /// </summary>
        internal static string strBackUp {
            get {
                return ResourceManager.GetString("strBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created.
        /// </summary>
        internal static string strBackupCreated {
            get {
                return ResourceManager.GetString("strBackupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string strDate {
            get {
                return ResourceManager.GetString("strDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string strDuration {
            get {
                return ResourceManager.GetString("strDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file was renamed to.
        /// </summary>
        internal static string strFileRenamed {
            get {
                return ResourceManager.GetString("strFileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file was restored.
        /// </summary>
        internal static string strFileRestored {
            get {
                return ResourceManager.GetString("strFileRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string strFirstName {
            get {
                return ResourceManager.GetString("strFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string strId {
            get {
                return ResourceManager.GetString("strId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string strIn {
            get {
                return ResourceManager.GetString("strIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Admin.
        /// </summary>
        internal static string strIsAdmin {
            get {
                return ResourceManager.GetString("strIsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string strLastName {
            get {
                return ResourceManager.GetString("strLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string strLogin {
            get {
                return ResourceManager.GetString("strLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login/Password does not exist !.
        /// </summary>
        internal static string strLoginPasswordIsNotExists {
            get {
                return ResourceManager.GetString("strLoginPasswordIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string strMessage {
            get {
                return ResourceManager.GetString("strMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not at work.
        /// </summary>
        internal static string strNotAtWork {
            get {
                return ResourceManager.GetString("strNotAtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the administrator can view this form.
        /// </summary>
        internal static string strOnlyAdminCanViewForm {
            get {
                return ResourceManager.GetString("strOnlyAdminCanViewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string strOut {
            get {
                return ResourceManager.GetString("strOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string strRestore {
            get {
                return ResourceManager.GetString("strRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show In List.
        /// </summary>
        internal static string strShowInList {
            get {
                return ResourceManager.GetString("strShowInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        internal static string strUpdateFailed {
            get {
                return ResourceManager.GetString("strUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful.
        /// </summary>
        internal static string strUpdateSuccessful {
            get {
                return ResourceManager.GetString("strUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string strUser {
            get {
                return ResourceManager.GetString("strUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string strUsers {
            get {
                return ResourceManager.GetString("strUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What.
        /// </summary>
        internal static string strWhat {
            get {
                return ResourceManager.GetString("strWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        internal static string strWhen {
            get {
                return ResourceManager.GetString("strWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string strWorker {
            get {
                return ResourceManager.GetString("strWorker", resourceCulture);
            }
        }
    }
}
